# Generated by Django 2.2.3 on 2019-07-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(blank=True, max_length=200, null=True)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/photos/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Gallery')),
            ],
        ),
    ]
